# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLab2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_lab2(self):
    self.driver.get("https://demo.opencart.com/")
    self.driver.set_window_size(1296, 688)
    self.driver.find_element(By.CSS_SELECTOR, ".col:nth-child(2) button:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".list-inline-item:nth-child(4) .d-none").click()
    elements = self.driver.find_elements(By.LINK_TEXT, "iPhone")
    assert len(elements) > 0
  
