file=open("f1.txt","r")
# content=file.read()
content=file.readline()
content1=file.readlines()
print(content)
print(content1)
file.close()

file=open("f1.txt","a")
file.write("\n New Line Added")
file.close()

file=open("f1.txt","w")
file.write("Hello Python")
file.write("\nThis is my write example")
file.close()
